import type { Metadata } from "next";
import { ProductPage } from "../components/product-page";

export const metadata: Metadata = {
  title: "ChainOps — Infrastructure-as-Code for Validators | Celara",
  description: "Deploy blockchain validators with Terraform. One-command deployments for Ethereum and Solana.",
};

export default function ChainOps() {
  return (
    <ProductPage
      name="ChainOps"
      tagline="Infrastructure-as-Code for validators"
      description="Deploy blockchain validators with a single command. ChainOps generates Terraform configurations for AWS with chain-specific defaults — instance types, storage sizes, security groups, and monitoring. Includes cost estimation before you deploy, state tracking across deployments, and templates for Ethereum and Solana validators."
      installCmd="pip install chainops"
      chains={["Ethereum", "Solana"]}
      features={[
        "One-command validator deployment to AWS",
        "Terraform-based infrastructure (auditable, reproducible)",
        "Chain-specific defaults (instance type, storage, networking)",
        "Cost estimation before deployment",
        "Dry-run mode to preview changes",
        "State tracking across deployments",
        "Security hardening (firewall rules, SSH lockdown)",
        "Deployment listing and status tracking",
        "Destroy command with confirmation",
      ]}
      quickStart={[
        {
          title: "Initialize and deploy an Ethereum validator",
          language: "bash",
          code: `pip install chainops

# Initialize config
chainops init ethereum --network mainnet --region us-east-1

# Review the generated config
cat chainops.yaml

# Estimate costs before deploying
chainops estimate

# Preview what Terraform will create
chainops deploy --dry-run

# Deploy for real
chainops deploy`,
        },
        {
          title: "Initialize a Solana validator",
          language: "bash",
          code: `chainops init solana --network mainnet --region us-west-2

# Solana defaults: r6i.2xlarge, 2TB storage
# Estimated cost: ~$715/month (or ~$263 with spot instances)`,
        },
        {
          title: "chainops.yaml configuration",
          language: "yaml",
          code: `# Generated by chainops init
name: ethereum-validator
chain: ethereum
network: mainnet
provider: aws
region: us-east-1
compute:
  instance_type: t3.xlarge
  storage_size: 2000        # GB
  spot_instances: false      # Enable for ~70% savings`,
        },
        {
          title: "Manage deployments",
          language: "bash",
          code: `# Check validator status
chainops status

# List all deployments
chainops list

# Destroy infrastructure
chainops destroy`,
        },
      ]}
      cliReference={[
        { command: "chainops init ethereum --network mainnet", description: "Initialize Ethereum validator config" },
        { command: "chainops init solana --network mainnet", description: "Initialize Solana validator config" },
        { command: "chainops deploy", description: "Deploy validator infrastructure" },
        { command: "chainops deploy --dry-run", description: "Preview Terraform plan without deploying" },
        { command: "chainops deploy --auto-approve", description: "Deploy without confirmation prompt" },
        { command: "chainops estimate", description: "Show monthly cost estimate" },
        { command: "chainops status", description: "Check validator status" },
        { command: "chainops list", description: "List all tracked deployments" },
        { command: "chainops destroy", description: "Destroy validator infrastructure" },
        { command: "chainops chains", description: "List supported blockchains with defaults" },
      ]}
      docs={[
        {
          heading: "How It Works",
          content: `ChainOps generates Terraform configurations from your chainops.yaml file:

1. chainops init — Creates a YAML config with chain-specific defaults
2. chainops deploy — Copies Terraform templates, generates terraform.tfvars, runs terraform init + plan + apply
3. chainops status — Queries Terraform state for deployment info
4. chainops destroy — Runs terraform destroy

Templates live in the templates/ directory. Each chain has its own template with:
• EC2 instance configuration (AMI, instance type, storage)
• Security groups (SSH, P2P ports, RPC ports)
• CloudWatch monitoring
• Automated node software installation via cloud-init`,
        },
        {
          heading: "Cost Estimates",
          content: `Ethereum Validator (t3.xlarge):
• EC2: $120/mo (or $36/mo with spot)
• EBS 2TB gp3: $160/mo
• Data transfer ~500GB: $45/mo
• CloudWatch: $10/mo
• Total: ~$335/mo ($211/mo with spot)

Solana Validator (r6i.2xlarge):
• EC2: $360/mo (or $108/mo with spot)
• EBS Ledger 2TB: $200/mo
• EBS Accounts 500GB: $50/mo
• Data transfer ~1TB: $90/mo
• CloudWatch: $15/mo
• Total: ~$715/mo ($463/mo with spot)

Enable spot instances in chainops.yaml for ~70% compute savings. Not recommended for mainnet validators due to interruption risk.`,
        },
        {
          heading: "Prerequisites",
          content: `• Terraform >= 1.0 installed and in PATH
• AWS credentials configured (aws configure or environment variables)
• Sufficient AWS quotas for the instance type in your region
• An SSH key pair for node access`,
        },
      ]}
      sourceUrl="https://github.com/jtaylortech/celara-homepage/tree/main/chainops"
    />
  );
}
