export default function ChainOpsDocs() {
  return (
    <div className="space-y-16">
      <section>
        <h1 className="text-3xl font-bold mb-4">ChainOps</h1>
        <p className="text-[var(--muted)] leading-relaxed">Deploy blockchain validators with a single command. Terraform-based infrastructure for AWS with chain-specific defaults, cost estimation, and state tracking.</p>
        <p className="text-[var(--muted)] mt-2"><strong className="text-[var(--text)]">Supported chains:</strong> Ethereum, Solana</p>
      </section>

      <section id="quick-start">
        <h2 className="text-xl font-bold mb-4">Quick Start</h2>
        <Pre code={`pip install chainops

chainops init ethereum --network mainnet --region us-east-1
chainops estimate          # See costs before deploying
chainops deploy --dry-run  # Preview Terraform plan
chainops deploy            # Deploy for real`} />
      </section>

      <section id="how-it-works">
        <h2 className="text-xl font-bold mb-4">How It Works</h2>
        <ol className="text-sm text-[var(--muted)] space-y-2 list-decimal list-inside">
          <li><code className="text-emerald-400">chainops init</code> — Creates chainops.yaml with chain-specific defaults (instance type, storage, region)</li>
          <li><code className="text-emerald-400">chainops deploy</code> — Copies Terraform templates, generates terraform.tfvars, runs <code className="text-emerald-400">terraform init → plan → apply</code></li>
          <li><code className="text-emerald-400">chainops status</code> — Queries Terraform state for deployment info (IP, status, region)</li>
          <li><code className="text-emerald-400">chainops destroy</code> — Runs <code className="text-emerald-400">terraform destroy</code> with confirmation</li>
        </ol>
        <Pre code={`# chainops.yaml (generated by init)
name: ethereum-validator
chain: ethereum
network: mainnet
provider: aws
region: us-east-1
compute:
  instance_type: t3.xlarge
  storage_size: 2000
  spot_instances: false`} />
      </section>

      <section id="costs">
        <h2 className="text-xl font-bold mb-4">Cost Estimates</h2>
        <div className="text-sm text-[var(--muted)] space-y-4">
          <div>
            <h3 className="font-semibold text-[var(--text)] mb-1">Ethereum (t3.xlarge)</h3>
            <p>EC2: $120/mo • EBS 2TB: $160/mo • Network: $45/mo • CloudWatch: $10/mo</p>
            <p className="font-medium">Total: ~$335/mo ($211/mo with spot instances)</p>
          </div>
          <div>
            <h3 className="font-semibold text-[var(--text)] mb-1">Solana (r6i.2xlarge)</h3>
            <p>EC2: $360/mo • Ledger 2TB: $200/mo • Accounts 500GB: $50/mo • Network: $90/mo • CloudWatch: $15/mo</p>
            <p className="font-medium">Total: ~$715/mo ($463/mo with spot instances)</p>
          </div>
        </div>
      </section>

      <section id="cli">
        <h2 className="text-xl font-bold mb-4">CLI Reference</h2>
        <Table rows={[
          ["chainops init <chain> --network mainnet", "Initialize validator config"],
          ["chainops deploy", "Deploy infrastructure"],
          ["chainops deploy --dry-run", "Preview Terraform plan"],
          ["chainops deploy --auto-approve", "Deploy without confirmation"],
          ["chainops estimate", "Show monthly cost estimate"],
          ["chainops status", "Check validator status"],
          ["chainops list", "List all deployments"],
          ["chainops destroy", "Destroy infrastructure"],
          ["chainops chains", "List supported chains"],
        ]} />
      </section>
    </div>
  );
}

function Pre({ code }: { code: string }) {
  return <pre className="p-4 bg-[var(--bg)] border border-[var(--border)] rounded-lg text-sm overflow-x-auto mt-4"><code className="text-emerald-400">{code}</code></pre>;
}
function Table({ rows }: { rows: string[][] }) {
  return (
    <div className="border border-[var(--border)] rounded-lg overflow-hidden">
      <table className="w-full text-sm"><thead><tr className="bg-[var(--bg)]"><th className="text-left px-4 py-2 font-medium">Command</th><th className="text-left px-4 py-2 font-medium">Description</th></tr></thead>
        <tbody>{rows.map((r) => (<tr key={r[0]} className="border-t border-[var(--border)]"><td className="px-4 py-2"><code className="text-emerald-400 text-xs">{r[0]}</code></td><td className="px-4 py-2 text-[var(--muted)]">{r[1]}</td></tr>))}</tbody>
      </table>
    </div>
  );
}
